apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: php
spec:
  replicas: 5
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php:7.3-fpm-alpine
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: host-path
        ports:
        - containerPort: 9000
      volumes:
      - name: host-path
        hostPath:
          path: /www
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: ClusterIP
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
